CREATE TABLE User (
	Id INT AUTO_INCREMENT NOT NULL,
	UUID VARCHAR(255),
	Created TIMESTAMP,
	Active BOOLEAN,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Password VARCHAR(255),
	Last_Login TIMESTAMP,
	Modified TIMESTAMP,
	Token VARCHAR(255),
	PRIMARY KEY (Id)
);